from __future__ import annotations

from app.schemas import AIResponse, AnalyzeResponse

_DISCLAIMER = "Generated by the built-in deterministic assistant. Connect an AI provider for richer, model-written guidance."


class DeterministicProvider:
    """Default provider. Produces useful, template-based output with no external API.

    It lets the AI endpoints work out of the box and keeps the same response shape a real
    model provider would return, so swapping in OpenAI/Anthropic later changes nothing for callers.
    """

    name = "deterministic"
    enabled = True

    def summarize(self, analysis: AnalyzeResponse) -> AIResponse:
        lines = [
            f"Pipeline scored {analysis.score}/100 (grade {analysis.grade}) for the detected "
            f"{analysis.provider.replace('_', ' ')} configuration.",
            "",
            "Severity breakdown:",
        ]
        for severity, count in analysis.severity_counts.items():
            if count:
                lines.append(f"  - {severity}: {count}")
        if analysis.findings:
            top = analysis.findings[0]
            lines += ["", f"Most important issue: {top.title} ({top.severity}).", f"  {top.impact}"]
        else:
            lines += ["", "No risks were detected by the enabled checks."]
        lines += ["", "Recommended next steps:"]
        lines += [f"  {index}. {step}" for index, step in enumerate(analysis.recommended_next_steps, start=1)]
        return AIResponse(
            provider=self.name,
            enabled=True,
            title="Pipeline risk summary",
            content="\n".join(lines),
            disclaimer=_DISCLAIMER,
        )

    def remediate(self, analysis: AnalyzeResponse, finding_id: str | None) -> AIResponse:
        target = None
        if finding_id:
            target = next((item for item in analysis.findings if item.id == finding_id), None)
        if target is None and analysis.findings:
            target = analysis.findings[0]
        if target is None:
            return AIResponse(
                provider=self.name,
                enabled=True,
                title="Nothing to remediate",
                content="No findings were reported for this pipeline.",
                disclaimer=_DISCLAIMER,
            )
        body = [
            f"# {target.title}",
            f"Severity: {target.severity} · Category: {target.category}",
            "",
            "## Why it matters",
            target.impact,
            "",
            "## How to fix",
            target.remediation,
        ]
        if target.safer_example:
            body += ["", "## Safer example", "```", target.safer_example, "```"]
        return AIResponse(
            provider=self.name,
            enabled=True,
            title=f"Remediation: {target.title}",
            content="\n".join(body),
            disclaimer=_DISCLAIMER,
        )


class DisabledProvider:
    name = "none"
    enabled = False

    def summarize(self, analysis: AnalyzeResponse) -> AIResponse:
        return self._disabled()

    def remediate(self, analysis: AnalyzeResponse, finding_id: str | None) -> AIResponse:
        return self._disabled()

    def _disabled(self) -> AIResponse:
        return AIResponse(
            provider=self.name,
            enabled=False,
            title="AI assistant is disabled",
            content="Set AI_PROVIDER to 'deterministic' (or wire up a model provider) to enable AI summaries and remediation.",
            disclaimer=None,
        )


def get_provider(name: str):
    normalized = (name or "none").lower()
    if normalized in {"deterministic", "builtin", "local"}:
        return DeterministicProvider()
    # Real model providers (openai, anthropic) plug in here once configured with a key.
    return DisabledProvider()
